### ISSUE TITLE
NPM package not supporting events property

### ISSUE THREAD

**Issue by ahultgren** [yusufff/react-weekview#1]
Hi! I tried using your component; it looks neat and I thought it would save me some time. However, the compiled version on NPM seems to not match the typescript code. My IDE tells me that `<WeekView />` doesn't have an `events` property (and maybe others are missing as well?), and looking at the package code (https://www.npmjs.com/package/react-weekview?activeTab=code) there's no event property mentioned anywhere. I have no idea what's going on there. The end result is that events don't show.

Is this something that would be an easy fix for you? 

Cheers!

**Comment by yusufff** [comment]
Hi @ahultgren I have released v0.0.13 which includes event types. The `events` prop should be supported.
